export { isTypedArray, isArrayLike, default as isArray } from './array'
export { default as isEmpty } from './empty'
export { default as isEqual } from './eq'
export { default as default, default as is } from './is'
export { default as isValidNumber, isNegative, isPositive, isLt, isGt, isInt, isDec } from './number'
export { isPlainObject, isGlobal, isObjectLike } from './object'
export { default as isPrimitive } from './primitive'
export { default as isIterable } from './iterator'
export { isThenable } from './promise'
export { default as type } from './type'